-- Casa Melo Decor + Supabase
-- Execute este script no SQL Editor do Supabase.
-- Ele cria as tabelas usadas pelo site estático e libera acesso via chave anon.

create extension if not exists pgcrypto;

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  celular varchar(20) not null unique,
  senha text not null,
  foto text default '',
  receber_novidades boolean not null default false,
  ultimo_acesso timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.carrinhos (
  cliente_celular varchar(20) primary key references public.clientes(celular) on delete cascade,
  itens jsonb not null default '[]'::jsonb,
  atualizado_em timestamptz not null default now()
);

create table if not exists public.historico_compras (
  id bigint generated by default as identity primary key,
  cliente_celular varchar(20) not null references public.clientes(celular) on delete cascade,
  itens jsonb not null default '[]'::jsonb,
  data_compra timestamptz not null default now()
);

create table if not exists public.comentarios (
  id text primary key,
  nome text not null,
  celular varchar(20),
  foto text,
  nota smallint not null check (nota between 1 and 5),
  comentario text not null check (length(btrim(comentario)) > 0),
  data_avaliacao timestamptz not null default now(),
  criado_em timestamptz not null default now()
);

create index if not exists idx_comentarios_data on public.comentarios (data_avaliacao desc);
create index if not exists idx_historico_cliente_data on public.historico_compras (cliente_celular, data_compra desc);

create or replace function public.casamelo_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

DROP TRIGGER IF EXISTS trg_clientes_touch_updated_at ON public.clientes;
create trigger trg_clientes_touch_updated_at
before update on public.clientes
for each row
execute function public.casamelo_touch_updated_at();

alter table public.clientes enable row level security;
alter table public.carrinhos enable row level security;
alter table public.historico_compras enable row level security;
alter table public.comentarios enable row level security;

-- Políticas abertas para funcionar com site estático usando a chave anon.
-- Recomendação: substituir por RPC/Auth antes de usar em produção com dados sensíveis.
DROP POLICY IF EXISTS "clientes_public_access" ON public.clientes;
create policy "clientes_public_access" on public.clientes
for all
using (true)
with check (true);

DROP POLICY IF EXISTS "carrinhos_public_access" ON public.carrinhos;
create policy "carrinhos_public_access" on public.carrinhos
for all
using (true)
with check (true);

DROP POLICY IF EXISTS "historico_public_access" ON public.historico_compras;
create policy "historico_public_access" on public.historico_compras
for all
using (true)
with check (true);

DROP POLICY IF EXISTS "comentarios_public_access" ON public.comentarios;
create policy "comentarios_public_access" on public.comentarios
for all
using (true)
with check (true);
