-- Casa Melo Decor + Supabase (schema compatível com relacionamentos por cliente_id/carrinho_id)
-- Execute este script no SQL Editor do Supabase.

create extension if not exists pgcrypto;

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  celular varchar(20) not null unique,
  senha_hash text not null default '',
  foto text default '',
  receber_novidades boolean not null default false,
  ultimo_acesso timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  user_id uuid not null default auth.uid(),
  constraint fk_clientes_auth foreign key (user_id) references auth.users(id)
);

create table if not exists public.carrinhos (
  id uuid primary key default gen_random_uuid(),
  celular varchar(20),
  created_at timestamp without time zone default now(),
  cliente_id uuid,
  atualizado_em timestamp without time zone,
  status varchar default 'ativo',
  criado_em timestamp without time zone default now(),
  constraint fk_carrinho_cliente foreign key (cliente_id) references public.clientes(id)
);

create table if not exists public.produtos (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  preco numeric not null,
  ativo boolean default true,
  criado_em timestamp without time zone default now()
);

create table if not exists public.itens_carrinho (
  id uuid primary key default gen_random_uuid(),
  carrinho_id uuid,
  produto_id uuid,
  quantidade integer not null,
  preco_unitario numeric not null,
  criado_em timestamp without time zone default now(),
  constraint itens_carrinho_carrinho_id_fkey foreign key (carrinho_id) references public.carrinhos(id),
  constraint itens_carrinho_produto_id_fkey foreign key (produto_id) references public.produtos(id)
);

create table if not exists public.historico_compras (
  id bigint generated always as identity primary key,
  cliente_celular varchar(20) not null,
  itens jsonb not null default '[]'::jsonb,
  data_compra timestamptz not null default now(),
  user_id uuid,
  status varchar default 'pendente',
  cliente_id uuid,
  constraint fk_user foreign key (user_id) references auth.users(id),
  constraint fk_historico_cliente_id foreign key (cliente_id) references public.clientes(id)
);

create table if not exists public.itens_pedido (
  id integer generated by default as identity primary key,
  quantidade integer default 1,
  preco numeric,
  carrinho_id uuid,
  compra_id bigint,
  preco_unitario numeric not null,
  criado_em timestamp without time zone default now(),
  user_id uuid,
  produto_id uuid,
  constraint fk_itens_carrinho foreign key (carrinho_id) references public.carrinhos(id),
  constraint fk_itens_compra foreign key (compra_id) references public.historico_compras(id),
  constraint fk_itens_produto foreign key (produto_id) references public.produtos(id)
);

create table if not exists public.pedidos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid,
  status text default 'pendente',
  criado_em timestamp without time zone default now(),
  constraint pedidos_cliente_id_fkey foreign key (cliente_id) references public.clientes(id)
);

create table if not exists public.comentarios (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  created_at timestamptz default now(),
  user_id uuid not null default gen_random_uuid(),
  cliente_id uuid,
  atualizado_em timestamp without time zone,
  mensagem text,
  criado_em timestamp without time zone default now(),
  constraint fk_comentarios_cliente foreign key (cliente_id) references public.clientes(id)
);

create index if not exists idx_clientes_celular on public.clientes(celular);
create index if not exists idx_carrinhos_cliente_id on public.carrinhos(cliente_id);
create index if not exists idx_itens_carrinho_carrinho on public.itens_carrinho(carrinho_id);
create index if not exists idx_historico_cliente_id_data on public.historico_compras(cliente_id, data_compra desc);
create index if not exists idx_comentarios_created_at on public.comentarios(created_at desc);

create or replace function public.casamelo_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

drop trigger if exists trg_clientes_touch_updated_at on public.clientes;
create trigger trg_clientes_touch_updated_at
before update on public.clientes
for each row
execute function public.casamelo_touch_updated_at();

alter table public.clientes enable row level security;
alter table public.carrinhos enable row level security;
alter table public.itens_carrinho enable row level security;
alter table public.historico_compras enable row level security;
alter table public.itens_pedido enable row level security;
alter table public.pedidos enable row level security;
alter table public.comentarios enable row level security;
alter table public.produtos enable row level security;

-- Políticas abertas para manter o site estático funcional com chave anon.
drop policy if exists "clientes_public_access" on public.clientes;
create policy "clientes_public_access" on public.clientes for all using (true) with check (true);

drop policy if exists "carrinhos_public_access" on public.carrinhos;
create policy "carrinhos_public_access" on public.carrinhos for all using (true) with check (true);

drop policy if exists "itens_carrinho_public_access" on public.itens_carrinho;
create policy "itens_carrinho_public_access" on public.itens_carrinho for all using (true) with check (true);

drop policy if exists "historico_public_access" on public.historico_compras;
create policy "historico_public_access" on public.historico_compras for all using (true) with check (true);

drop policy if exists "itens_pedido_public_access" on public.itens_pedido;
create policy "itens_pedido_public_access" on public.itens_pedido for all using (true) with check (true);

drop policy if exists "pedidos_public_access" on public.pedidos;
create policy "pedidos_public_access" on public.pedidos for all using (true) with check (true);

drop policy if exists "comentarios_public_access" on public.comentarios;
create policy "comentarios_public_access" on public.comentarios for all using (true) with check (true);

drop policy if exists "produtos_public_access" on public.produtos;
create policy "produtos_public_access" on public.produtos for all using (true) with check (true);
