-- Esquema PostgreSQL genérico para comentários e cadastro de clientes.
-- Execute conectado ao banco desejado (ex.: psql -d casamelodecor -f database/schema.sql)

CREATE TABLE IF NOT EXISTS comentarios (
  id TEXT PRIMARY KEY,
  nome TEXT NOT NULL,
  celular VARCHAR(20),
  foto TEXT,
  nota SMALLINT NOT NULL,
  comentario TEXT NOT NULL,
  data_avaliacao TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_comentarios_nota CHECK (nota BETWEEN 1 AND 5),
  CONSTRAINT chk_comentarios_comentario CHECK (length(btrim(comentario)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_comentarios_data ON comentarios (data_avaliacao DESC);

CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT NOT NULL,
  criado_em TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT usuarios_email_unico UNIQUE (email)
);
