-- Compatibilidade para projetos Supabase já criados com tabelas diferentes.
-- Este script preserva dados úteis e cria a estrutura esperada pelo site.
-- Execute no SQL Editor do Supabase se você já criou tabelas como `usuarios`
-- e uma `comentarios` com colunas `user_id` / `created_at`.

create extension if not exists pgcrypto;

create table if not exists public.clientes (
  id uuid primary key default gen_random_uuid(),
  nome text not null,
  celular varchar(20) not null unique,
  senha text not null default '',
  foto text default '',
  receber_novidades boolean not null default false,
  ultimo_acesso timestamptz,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now()
);

create table if not exists public.carrinhos (
  cliente_celular varchar(20) primary key references public.clientes(celular) on delete cascade,
  itens jsonb not null default '[]'::jsonb,
  atualizado_em timestamptz not null default now()
);

create table if not exists public.historico_compras (
  id bigint generated by default as identity primary key,
  cliente_celular varchar(20) not null references public.clientes(celular) on delete cascade,
  itens jsonb not null default '[]'::jsonb,
  data_compra timestamptz not null default now()
);

create table if not exists public.comentarios (
  id text primary key,
  nome text,
  celular varchar(20),
  foto text,
  nota smallint,
  comentario text,
  data_avaliacao timestamptz,
  criado_em timestamptz not null default now()
);

alter table public.comentarios
  add column if not exists celular varchar(20),
  add column if not exists foto text,
  add column if not exists nota smallint,
  add column if not exists comentario text,
  add column if not exists data_avaliacao timestamptz,
  add column if not exists criado_em timestamptz not null default now();

do $$
declare
  tem_usuarios boolean;
  tem_created_at boolean;
  tem_user_id boolean;
begin
  select to_regclass('public.usuarios') is not null into tem_usuarios;

  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'comentarios'
      and column_name = 'created_at'
  ) into tem_created_at;

  select exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'comentarios'
      and column_name = 'user_id'
  ) into tem_user_id;

  if tem_usuarios and tem_user_id then
    execute $sql$
      update public.comentarios c
      set
        nome = coalesce(nullif(c.nome, ''), u.nome, 'Cliente'),
        comentario = coalesce(nullif(c.comentario, ''), 'Comentário importado'),
        nota = coalesce(c.nota, 5)
      from public.usuarios u
      where c.user_id is not null
        and u.id = c.user_id
    $sql$;
  end if;

  if tem_created_at then
    execute $sql$
      update public.comentarios
      set
        data_avaliacao = coalesce(data_avaliacao, created_at, criado_em, now()),
        criado_em = coalesce(criado_em, created_at, now())
    $sql$;
  else
    update public.comentarios
    set
      data_avaliacao = coalesce(data_avaliacao, criado_em, now()),
      criado_em = coalesce(criado_em, now());
  end if;
end
$$;

update public.comentarios
set
  nome = coalesce(nullif(nome, ''), 'Cliente'),
  comentario = coalesce(nullif(comentario, ''), 'Comentário importado'),
  nota = coalesce(nota, 5),
  data_avaliacao = coalesce(data_avaliacao, criado_em, now()),
  criado_em = coalesce(criado_em, now())
where true;

alter table public.comentarios alter column nome set not null;
alter table public.comentarios alter column comentario set not null;
alter table public.comentarios alter column nota set not null;
alter table public.comentarios alter column data_avaliacao set not null;

alter table public.comentarios
  drop constraint if exists comentarios_nota_check;

alter table public.comentarios
  add constraint comentarios_nota_check check (nota between 1 and 5);

create index if not exists idx_comentarios_data on public.comentarios (data_avaliacao desc);
create index if not exists idx_historico_cliente_data on public.historico_compras (cliente_celular, data_compra desc);

create or replace function public.casamelo_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.atualizado_em = now();
  return new;
end;
$$;

DROP TRIGGER IF EXISTS trg_clientes_touch_updated_at ON public.clientes;
create trigger trg_clientes_touch_updated_at
before update on public.clientes
for each row
execute function public.casamelo_touch_updated_at();

alter table public.clientes enable row level security;
alter table public.carrinhos enable row level security;
alter table public.historico_compras enable row level security;
alter table public.comentarios enable row level security;

DROP POLICY IF EXISTS "clientes_public_access" ON public.clientes;
create policy "clientes_public_access" on public.clientes
for all
using (true)
with check (true);

DROP POLICY IF EXISTS "carrinhos_public_access" ON public.carrinhos;
create policy "carrinhos_public_access" on public.carrinhos
for all
using (true)
with check (true);

DROP POLICY IF EXISTS "historico_public_access" ON public.historico_compras;
create policy "historico_public_access" on public.historico_compras
for all
using (true)
with check (true);

DROP POLICY IF EXISTS "comentarios_public_access" ON public.comentarios;
create policy "comentarios_public_access" on public.comentarios
for all
using (true)
with check (true);
